image: nixos/nix

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - nix-shell --run 'hugo version'
    - nix-shell --run 'hugo --cleanDestinationDir --buildDrafts --buildExpired --buildFuture --templateMetrics --templateMetricsHints'

pages:
  stage: build
  script:
    - path="$(nix-build . --argstr baseURL 'https://dev.risson.space/')"
    - cp -r $path public
  artifacts:
    paths:
      - public

mr:
  stage: deploy
  script:
    - ./.gitlab/dotshabka-deploy.sh
  only:
    - master
